### PR TITLE
Battle function

### PR DESCRIPTION
**Pull request by btarg**
TODO: fix issues with this command... I have reverted it in case anything changed but don't know what went wrong.

### CODE REVIEW

**Comment by asxlvm** [comment]
Hey! For now I have imported the latest code in main, I have imported some of the commands, not including help since it doesn't work, let me know if something's missing ^-^

**Comment by btarg** [comment]
> Hey! For now I have imported the latest code in main, I have imported some of the commands, not including help since it doesn't work, let me know if something's missing ^-^

In my testing the help command worked (it also worked when testing the DogeBoss' Brother bot, based on the main branch of my repo), but it requires the commands to have docstrings which is extra work, and my IDE started messing up while writing it so I may have made some mistakes that weren't corrected. I'll probably come back to it and update, but for now we might as well focus on other commands like adding functionality and fun stuff.

**Comment by btarg** [comment]
> > Hey! For now I have imported the latest code in main, I have imported some of the commands, not including help since it doesn't work, let me know if something's missing ^-^
> 
> In my testing the help command worked (it also worked when testing the DogeBoss' Brother bot, based on the main branch of my repo), but it requires the commands to have docstrings which is extra work, and my IDE started messing up while writing it so I may have made some mistakes that weren't corrected. I'll probably come back to it and update, but for now we might as well focus on other commands like adding functionality and fun stuff.

**Comment by asxlvm** [comment]
Yeah okie, right now I figured out the help command an easier way provided by the creator of dogehouse.py! I'll put it in the source code right now ^-^

**Pull request closed without merging**
